# Generated by Django 4.2.7 on 2024-12-06 21:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_group",
                    models.BooleanField(
                        default=False, verbose_name="conversation de groupe"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="nom"),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="participants",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Succès"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False, verbose_name="lu")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="lu le"),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=255, verbose_name="lien"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="message_files/",
                        verbose_name="fichier",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.conversation",
                        verbose_name="conversation",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lu par",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="titre")),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                        verbose_name="priorité",
                    ),
                ),
                (
                    "target_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("ADMIN", "Administrateur"),
                                ("TEACHER", "Enseignant"),
                                ("STUDENT", "Étudiant"),
                            ],
                            max_length=20,
                        ),
                        size=None,
                        verbose_name="rôles ciblés",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(verbose_name="date de début")),
                ("end_date", models.DateTimeField(verbose_name="date de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="announcements/",
                        verbose_name="pièce jointe",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "annonce",
                "verbose_name_plural": "annonces",
                "ordering": ["-created_at"],
            },
        ),
    ]
